
---

Organizations:

    - &OrdererOrg
        Name: OrdererOrg
        ID: OrdererMSP
        MSPDir: crypto-config/ordererOrganizations/votebook.com/msp
        Policies:
            Readers:
                Type: Signature
                Rule: "OR('OrdererMSP.member')"
            Writers:
                Type: Signature
                Rule: "OR('OrdererMSP.member')"
            Admins:
                Type: Signature
                Rule: "OR('OrdererMSP.admin')"

    - &AuthOrg
        Name: AuthOrgMSP
        ID: AuthOrgMSP
        MSPDir: crypto-config/peerOrganizations/authorg.votebook.com/msp
        Policies:
            Readers:
                Type: Signature
                Rule: "OR('AuthOrgMSP.admin', 'AuthOrgMSP.peer', 'AuthOrgMSP.client')"
            Writers:
                Type: Signature
                Rule: "OR('AuthOrgMSP.admin', 'AuthOrgMSP.client')"
            Admins:
                Type: Signature
                Rule: "OR('AuthOrgMSP.admin')"
        AnchorPeers:
            - Host: peer0.authorg.votebook.com
              Port: 7051

    - &VoteOrg
        Name: VoteOrgMSP
        ID: VoteOrgMSP
        MSPDir: crypto-config/peerOrganizations/voteorg.votebook.com/msp
        Policies:
            Readers:
                Type: Signature
                Rule: "OR('VoteOrgMSP.admin', 'VoteOrgMSP.peer', 'VoteOrgMSP.client')"
            Writers:
                Type: Signature
                Rule: "OR('VoteOrgMSP.admin', 'VoteOrgMSP.client')"
            Admins:
                Type: Signature
                Rule: "OR('VoteOrgMSP.admin')"
        AnchorPeers:
            - Host: peer0.voteorg.votebook.com
              Port: 9051


Capabilities:

    Channel: &ChannelCapabilities
        V1_3: true
    Orderer: &OrdererCapabilities
        V1_1: true
    Application: &ApplicationCapabilities
        V1_3: true
        V1_2: false
        V1_1: false


Application: &ApplicationDefaults

    Organizations:
    Policies:
        Readers:
            Type: ImplicitMeta
            Rule: "ANY Readers"
        Writers:
            Type: ImplicitMeta
            Rule: "ANY Writers"
        Admins:
            Type: ImplicitMeta
            Rule: "MAJORITY Admins"

    Capabilities:
        <<: *ApplicationCapabilities


Orderer: &OrdererDefaults

    OrdererType: solo
    Addresses:
        - orderer.votebook.com:7050
    BatchTimeout: 2s
    BatchSize:
        MaxMessageCount: 10
        AbsoluteMaxBytes: 99 MB
        PreferredMaxBytes: 512 KB
    Kafka:
        Brokers:
            - 127.0.0.1:9092
    Organizations:
    Policies:
        Readers:
            Type: ImplicitMeta
            Rule: "ANY Readers"
        Writers:
            Type: ImplicitMeta
            Rule: "ANY Writers"
        Admins:
            Type: ImplicitMeta
            Rule: "MAJORITY Admins"
        BlockValidation:
            Type: ImplicitMeta
            Rule: "ANY Writers"


Channel: &ChannelDefaults
    Policies:
        Readers:
            Type: ImplicitMeta
            Rule: "ANY Readers"
        Writers:
            Type: ImplicitMeta
            Rule: "ANY Writers"
        Admins:
            Type: ImplicitMeta
            Rule: "MAJORITY Admins"
    Capabilities:
        <<: *ChannelCapabilities


Profiles:

    TwoOrgsOrdererGenesis: 
        <<: *ChannelDefaults
        Orderer:
            <<: *OrdererDefaults
            Organizations:
                - *OrdererOrg
            Capabilities:
                <<: *OrdererCapabilities
        Consortiums:
            SampleConsortium:
                Organizations:
                    - *AuthOrg
                    - *VoteOrg
            AuthConsortium:
                Organizations:
                    - *AuthOrg
            VoteConsortium:
                Organizations:
                  - *VoteOrg

    AuthChannel:
        Consortium: AuthConsortium
        <<: *ChannelDefaults
        Application:
            <<: *ApplicationDefaults
            Organizations:
                - *AuthOrg
            Capabilities:
                <<: *ApplicationCapabilities

    VoteChannel:
        Consortium: VoteConsortium
        <<: *ChannelDefaults
        Application:
            <<: *ApplicationDefaults
            Organizations:
                - *VoteOrg
            Capabilities:
                <<: *ApplicationCapabilities
        
    SampleDevModeKafka:
        <<: *ChannelDefaults
        Capabilities:
            <<: *ChannelCapabilities
        Orderer:
            <<: *OrdererDefaults
            OrdererType: kafka
            Kafka:
                Brokers:
                - kafka.votebook.com:9092

            Organizations:
            - *OrdererOrg
            Capabilities:
                <<: *OrdererCapabilities
        Application:
            <<: *ApplicationDefaults
            Organizations:
            - <<: *OrdererOrg
        Consortiums:
            SampleConsortium:
                Organizations:
                - *AuthOrg
                - *VoteOrg
            AuthConsortium:
                Organizations:
                    - *AuthOrg
            VoteConsortium:
                Organizations:
                  - *VoteOrg

    SampleMultiNodeEtcdRaft:  
        <<: *ChannelDefaults
        Capabilities:
            <<: *ChannelCapabilities
        Orderer:
            <<: *OrdererDefaults
            OrdererType: etcdraft
            EtcdRaft:
                Consenters:
                - Host: orderer.votebook.com
                  Port: 7050
                  ClientTLSCert: crypto-config/ordererOrganizations/votebook.com/orderers/orderer.votebook.com/tls/server.crt
                  ServerTLSCert: crypto-config/ordererOrganizations/votebook.com/orderers/orderer.votebook.com/tls/server.crt
                - Host: orderer2.votebook.com
                  Port: 7050
                  ClientTLSCert: crypto-config/ordererOrganizations/votebook.com/orderers/orderer2.votebook.com/tls/server.crt
                  ServerTLSCert: crypto-config/ordererOrganizations/votebook.com/orderers/orderer2.votebook.com/tls/server.crt
                - Host: orderer3.votebook.com
                  Port: 7050
                  ClientTLSCert: crypto-config/ordererOrganizations/votebook.com/orderers/orderer3.votebook.com/tls/server.crt
                  ServerTLSCert: crypto-config/ordererOrganizations/votebook.com/orderers/orderer3.votebook.com/tls/server.crt
                - Host: orderer4.votebook.com
                  Port: 7050
                  ClientTLSCert: crypto-config/ordererOrganizations/votebook.com/orderers/orderer4.votebook.com/tls/server.crt
                  ServerTLSCert: crypto-config/ordererOrganizations/votebook.com/orderers/orderer4.votebook.com/tls/server.crt
                - Host: orderer5.votebook.com
                  Port: 7050
                  ClientTLSCert: crypto-config/ordererOrganizations/votebook.com/orderers/orderer5.votebook.com/tls/server.crt
                  ServerTLSCert: crypto-config/ordererOrganizations/votebook.com/orderers/orderer5.votebook.com/tls/server.crt
            Addresses:
                - orderer.votebook.com:7050
                - orderer2.votebook.com:7050
                - orderer3.votebook.com:7050
                - orderer4.votebook.com:7050
                - orderer5.votebook.com:7050

            Organizations:
            - *OrdererOrg
            Capabilities:
                <<: *OrdererCapabilities
        Application:
            <<: *ApplicationDefaults
            Organizations:
            - <<: *OrdererOrg
        Consortiums:
            SampleConsortium:
                Organizations:
                - *AuthOrg
                - *VoteOrg
            AuthConsortium:
                Organizations:
                    - *AuthOrg
            VoteConsortium:
                Organizations:
                  - *VoteOrg